services:
    chat_application.message.controller:
        class: Chat\ApplicationBundle\Controller\MessageController
        arguments: [@chat_application.message]
    chat_application.topic.controller:
        class: Chat\ApplicationBundle\Controller\TopicController
        arguments: [@chat_application.topic]
