imports:
    - { resource: controllers.yml }

parameters:
    chat_application.message.repository.class: Chat\ApplicationBundle\Repository\MessageRepository
    chat_application.message.entity.class: Chat\ApplicationBundle\Entity\Message
    chat_application.message.service.class: Chat\ApplicationBundle\Service\MessageService
    chat_application.topic.repository.class: Chat\ApplicationBundle\Repository\TopicRepository
    chat_application.topic.entity.class: Chat\ApplicationBundle\Entity\Topic
    chat_application.topic.service.class: Chat\ApplicationBundle\Service\TopicService
    chat_application.json_and_query_param_converter.class: Chat\ApplicationBundle\Request\ParamConverter\JsonAndQueryConverter
    chat_application.smart_param_converter.class: Chat\ApplicationBundle\Request\ParamConverter\SmartConverter

services:
    chat_application.message.repository:
        class: %chat_application.message.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%chat_application.message.entity.class%]
    chat_application.message:
        class: %chat_application.message.service.class%
        arguments: [@chat_application.message.repository]
    chat_application.topic.repository:
        class: %chat_application.topic.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%chat_application.topic.entity.class%]
    chat_application.topic:
        class: %chat_application.topic.service.class%
        arguments: [@chat_application.topic.repository]

    chat_application.json_and_query_param_converter:
        class: %chat_application.json_and_query_param_converter.class%
        tags:
            - { name: request.param_converter, priority: -3, converter: json_and_query }

    chat_application.smart_param_converter:
        class: %chat_application.smart_param_converter.class%
        tags:
            - { name: request.param_converter, priority: -2, converter: smart }
        arguments: [@chat_application.topic]
