<?php

namespace Chat\ApplicationBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Chat\ApplicationBundle\Entity\Topic;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends EntityRepository
{
    /**
     * Persist a Topic entity to database
     *
     * @param Topic $topic
     *
     * @return int Id of the saved Topic
     */
    public function save(Topic $topic)
    {
        $entityManager = $this->getEntityManager();

        $entityManager->persist($topic);
        $entityManager->flush($topic);

        return $topic->getId();
    }

    /**
     * Remove a Topic entity from database
     *
     * @param Topic $topic
     */
    public function remove(Topic $topic)
    {
        $entityManager = $this->getEntityManager();

        $entityManager->remove($topic);
        $entityManager->flush($topic);
    }
}
